
version: "2.4"
services:
  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-prerelease-20210114
    container_name: selenium-hub
    ports:
      - "4545:4444"
    networks:
      - selenium
  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - NODE_MAX_INSTANCE=2
      - NODE_MAX_SESSION=2
    networks:
      - selenium
networks:
  selenium:
    name: selenium
